(() => {
"use strict";
const KEY="also-crm-intelligence-fixed-v1";
const DEFAULT_AZURE={endpoint:"",deployment:"",apiVersion:"2025-04-01-preview",apiKey:"",status:{state:"none",message:""}};
const TAG_MAP={
 manufacturers:{HP:["hp","hewlett packard","hp inc"],Canon:["canon"],Epson:["epson"],Ricoh:["ricoh"],Xerox:["xerox"],Lenovo:["lenovo"],Dell:["dell"],Cisco:["cisco"],Fortinet:["fortinet"],Sophos:["sophos"],Microsoft:["microsoft"]},
 technologies:{Azure:["azure"],"Microsoft 365":["microsoft 365","office 365","m365"],Teams:["teams"],Intune:["intune"],VMware:["vmware"],Veeam:["veeam"],"Endpoint Security":["endpoint security"],Firewall:["firewall"]},
 business_areas:{"Managed Services":["managed services","managed service","msp"],"Managed Print Services":["managed print","print management","output management"],"Cloud Services":["cloud services","cloud computing"],"IT Security":["it security","cyber security","security"],"Document Management":["document management"],"Networking":["networking","network"]}
};
const CLUSTERS=[
 {id:"cloud",name:"Microsoft Cloud Zielkunden",all:["Microsoft"],any:["Azure","Microsoft 365","Cloud Services","Managed Services"]},
 {id:"print",name:"Managed Print Zielkunden",all:[],any:["HP","Canon","Epson","Ricoh","Managed Print Services","Document Management"]},
 {id:"security",name:"Security Zielkunden",all:[],any:["Fortinet","Sophos","Cisco","Firewall","Endpoint Security","IT Security"]},
 {id:"workplace",name:"Modern Workplace Zielkunden",all:["Microsoft"],any:["Microsoft 365","Teams","Intune","Managed Services"]}
];
let state=loadState(), view="dashboard", selected=null, logLines=[];
function loadState(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Array.isArray(s.companies))return hydrate(s)}catch(e){}return hydrate({companies:[],azure:DEFAULT_AZURE,createdAt:Date.now()})}
function hydrate(s){s.azure=Object.assign({},DEFAULT_AZURE,s.azure||{});s.azure.status=Object.assign({state:"none",message:""},s.azure.status||{});s.companies=(s.companies||[]).map(normalizeCompany);return s}
function normalizeCompany(c){return Object.assign({company_id:"",company_name:"",website_url:"",legal_form:"",industry:"",nace_code:"",nace_label:"",employee_range:"",city:"",country:"",crm_revenue:0,raw_tags:[],tags:{manufacturers:[],technologies:[],business_areas:[]},evidence:[],crawl_status:"pending",last_crawled_at:"",opportunity_score:0,priority:"D",clusters:[],notes:""},c,{raw_tags:Array.isArray(c.raw_tags)?c.raw_tags:[],tags:Object.assign({manufacturers:[],technologies:[],business_areas:[]},c.tags||{}),evidence:Array.isArray(c.evidence)?c.evidence:[]})}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function toast(msg){const e=document.querySelector("#toast");e.textContent=msg;e.classList.remove("hidden");setTimeout(()=>e.classList.add("hidden"),3000)}
function badge(v){let c="gray-b";const x=String(v||"").toLowerCase();if(["a","high","success","successfully crawled","connected","ok","hoch"].includes(x))c="green-b";if(["b","medium","testing","in arbeit"].includes(x))c="amber-b";if(["c","d","low","failed","error","pending"].includes(x))c="red-b";if(x.includes("azure")||x.includes("technology"))c="blue-b";return `<span class="badge ${c}">${esc(v||"–")}</span>`}
function tags(c){return [...c.tags.manufacturers,...c.tags.technologies,...c.tags.business_areas]}
function allTags(){const m=new Map();state.companies.forEach(c=>tags(c).forEach(t=>m.set(t,(m.get(t)||0)+1)));return [...m.entries()].sort((a,b)=>b[1]-a[1])}
function score(c){let s=0;s+=Math.min(25,Number(c.crm_revenue||0)/20000);s+=Math.min(20,tags(c).length*3);s+=c.website_url?15:0;s+=c.nace_code?10:0;s+=c.employee_range?10:0;s+=c.crawl_status==="success"?20:0;return Math.min(100,Math.round(s))}
function priority(s){return s>=75?"A":s>=55?"B":s>=35?"C":"D"}
function evidence(text,term,source="Mock website"){return {term,source_url:source,evidence:text.slice(0,240),confidence:0.86}}
function crawlCompany(c){const base=(c.company_name+" "+c.industry+" "+c.raw_tags.join(" ")+" "+(c.website_url||"")).toLowerCase();const result={manufacturers:[],technologies:[],business_areas:[]},ev=[];for(const group of Object.keys(TAG_MAP))for(const [canon,terms] of Object.entries(TAG_MAP[group])){const hit=terms.find(t=>base.includes(t));if(hit){result[group].push(canon);ev.push(evidence(`Treffer „${hit}“ im CRM-/Website-Kontext.`,hit,c.website_url||"CRM"))}}Object.keys(result).forEach(k=>result[k]=[...new Set(result[k])]);c.tags=result;c.evidence=ev;c.crawl_status="success";c.last_crawled_at=new Date().toISOString();c.opportunity_score=score(c);c.priority=priority(c.opportunity_score);c.clusters=matchClusters(c);save();return c}
function matchClusters(c){const ts=new Set(tags(c));return CLUSTERS.filter(x=>x.all.every(t=>ts.has(t))&&(x.any.length===0||x.any.some(t=>ts.has(t)))).map(x=>x.name)}
function importSample(){fetch("data/sample_companies.json").then(r=>r.json()).then(rows=>{state.companies=rows.map(normalizeCompany);save();render();toast("Beispieldaten geladen")}).catch(()=>toast("Beispieldaten konnten bei file:// nicht geladen werden. JSON-Import verwenden."))}
function page(title,sub,body,actions=""){return `<section class="main"><div class="page-head"><div><h2>${title}</h2><div class="muted">${sub}</div></div><div class="toolbar">${actions}</div></div>${body}</section>`}
function dashboard(){const cs=state.companies, crawled=cs.filter(c=>c.crawl_status==="success").length, avg=cs.length?Math.round(cs.reduce((a,c)=>a+c.opportunity_score,0)/cs.length):0;return page("Dashboard","Übersicht über CRM-Anreicherung, Tags und Vertriebschancen",`<div class="grid grid-4"><div class="card kpi">CRM-Unternehmen<b>${cs.length}</b><small>importiert / erfasst</small></div><div class="card kpi">Crawls erfolgreich<b>${crawled}</b><small>von ${cs.length}</small></div><div class="card kpi">Ø Opportunity Score<b>${avg}</b><small>von 100</small></div><div class="card kpi">CRM Cluster<b>${CLUSTERS.length}</b><small>regelbasiert aktiv</small></div></div><div class="grid grid-2" style="margin-top:14px"><div class="panel"><div class="split"><h3>Top-Tags</h3><button class="btn green" data-action="crawlAll">Alle crawlen</button></div>${allTags().slice(0,12).map(([t,n])=>`<div style="margin:12px 0"><div class="split"><span>${esc(t)}</span><b>${n}</b></div><div class="bar"><i style="width:${cs.length?Math.round(n/cs.length*100):0}%"></i></div></div>`).join("")||'<div class="empty">Noch keine Tags vorhanden.</div>'}</div><div class="panel"><h3>Prioritäten</h3>${["A","B","C","D"].map(p=>{const n=cs.filter(c=>c.priority===p).length;return `<div class="split" style="padding:13px 0;border-bottom:1px solid var(--line)">${badge(p)}<b>${n} Unternehmen</b></div>`}).join("")}</div></div>`)}
function companies(){const q=(document.querySelector("#companySearch")?.value||"").toLowerCase();const rows=state.companies.filter(c=>(c.company_name+" "+c.company_id+" "+c.industry+" "+tags(c).join(" ")).toLowerCase().includes(q));return page("Unternehmen","CRM-Stammdaten bearbeiten, analysieren und crawlen",`<div class="toolbar"><input id="companySearch" class="search" placeholder="Unternehmen, Branche oder Tag suchen" value="${esc(q)}" oninput="render()"><select id="priorityFilter" onchange="render()"><option value="">Alle Prioritäten</option>${["A","B","C","D"].map(x=>`<option ${document.querySelector("#priorityFilter")?.value===x?"selected":""}>${x}</option>`).join("")}</select></div><div class="panel table-wrap" style="margin-top:14px"><table class="table"><tr><th>Unternehmen</th><th>Branche / NACE</th><th>Tags</th><th>Score</th><th>Priorität</th><th>Status</th><th>Aktionen</th></tr>${rows.filter(c=>{const f=document.querySelector("#priorityFilter")?.value;return !f||c.priority===f}).map(c=>`<tr><td><b>${esc(c.company_name)}</b><div class="muted">${esc(c.company_id)} · ${esc(c.city)}</div></td><td>${esc(c.industry)}<div class="muted">${esc(c.nace_code)}</div></td><td>${tags(c).slice(0,7).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</td><td><b>${c.opportunity_score}</b></td><td>${badge(c.priority)}</td><td>${badge(c.crawl_status)}</td><td><div class="toolbar"><button class="btn green" data-crawl="${esc(c.company_id)}">Crawlen</button><button class="btn" data-edit="${esc(c.company_id)}">Bearbeiten</button><button class="btn danger" data-delete="${esc(c.company_id)}">Löschen</button></div></td></tr>`).join("")||'<tr><td colspan="7" class="empty">Keine Unternehmen gefunden.</td></tr>'}</table></div>`,"<button class=\"btn primary\" data-action=\"add\">+ Unternehmen hinzufügen</button>")}
function raw(){return page("Raw Data Explorer","Unveränderte CRM- und Crawl-Felder bleiben nachvollziehbar erhalten",`<div class="panel table-wrap"><table class="table"><tr><th>ID</th><th>Firmenname</th><th>Website</th><th>Rechtsform</th><th>Branche</th><th>NACE</th><th>Mitarbeiter</th><th>Ort</th><th>Raw Tags</th><th>Crawl</th><th>Aktualisiert</th></tr>${state.companies.map(c=>`<tr><td>${esc(c.company_id)}</td><td>${esc(c.company_name)}</td><td>${esc(c.website_url)}</td><td>${esc(c.legal_form)}</td><td>${esc(c.industry)}</td><td>${esc(c.nace_code)}</td><td>${esc(c.employee_range)}</td><td>${esc(c.city)}</td><td>${esc(c.raw_tags.join(" | "))}</td><td>${badge(c.crawl_status)}</td><td>${esc(c.last_crawled_at)}</td></tr>`).join("")}</table></div>`)}
function tagsView(){const pairs=allTags();return page("Tag Explorer","Normalisierte Hersteller-, Technologie- und Geschäftsfeld-Tags",`<div class="grid grid-3">${Object.entries(TAG_MAP).map(([g,map])=>`<div class="panel"><h3>${g==="manufacturers"?"Hersteller":g==="technologies"?"Technologien":"Geschäftsfelder"}</h3>${Object.keys(map).map(t=>{const n=state.companies.filter(c=>c.tags[g].includes(t)).length;return `<div class="split" style="padding:8px 0;border-bottom:1px solid var(--line)"><span>${esc(t)}</span><b>${n}</b></div>`}).join("")}</div>`).join("")}</div><div class="panel" style="margin-top:14px"><h3>Evidence-Treffer</h3>${state.companies.flatMap(c=>c.evidence.map(e=>`<div class="list-item"><b>${esc(c.company_name)} · ${esc(e.term)}</b><div>${esc(e.evidence)}</div><small class="muted">${esc(e.source_url)} · Confidence ${Math.round(e.confidence*100)}%</small></div>`)).join("")||'<div class="empty">Noch keine Evidence vorhanden.</div>'}</div>`)}
function clusters(){return page("CRM Cluster","Automatisch berechnete Zielgruppen für Kampagnen und CRM-Segmente",`<div class="grid grid-2">${CLUSTERS.map(cl=>{const members=state.companies.filter(c=>matchClusters(c).includes(cl.name));return `<div class="panel"><div class="split"><h3>${esc(cl.name)}</h3>${badge(members.length+" Treffer")}</div><p class="muted">Kriterien: ${[...cl.all,...cl.any].join(" · ")||"keine"}</p>${members.map(c=>`<div class="list-item"><b>${esc(c.company_name)}</b><div>${tags(c).map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div></div>`).join("")||'<div class="empty">Keine passenden Unternehmen. Tags ergänzen oder crawlen.</div>'}</div>`}).join("")}</div>`,"<button class=\"btn green\" data-action=\"exportClusters\">Cluster exportieren</button>")}
function sales(){const rows=[...state.companies].sort((a,b)=>b.opportunity_score-a.opportunity_score);return page("Sales Intelligence","Vertriebspriorisierung auf Basis von CRM-Daten und Enrichment",`<div class="panel table-wrap"><table class="table"><tr><th>Unternehmen</th><th>Opportunity Score</th><th>Priorität</th><th>Umsatz</th><th>Empfehlung</th><th>Cluster</th></tr>${rows.map(c=>`<tr><td><b>${esc(c.company_name)}</b><div class="muted">${esc(c.industry)}</div></td><td><span class="score">${c.opportunity_score}</span>/100</td><td>${badge(c.priority)}</td><td>${Number(c.crm_revenue||0).toLocaleString("de-DE")} €</td><td>${esc(c.priority==="A"?"Account-Review und Kampagne priorisieren":c.priority==="B"?"Gezielte Herstellerkampagne vorbereiten":"Daten ergänzen und qualifizieren")}</td><td>${c.clusters.map(x=>`<span class="tag">${esc(x)}</span>`).join("")||"–"}</td></tr>`).join("")}</table></div>`)}
function tender(){const rows=state.companies.map(c=>({company_id:c.company_id,company_name:c.company_name,capabilities:[...c.tags.business_areas,...c.tags.technologies],tender_categories:c.tags.business_areas,signals:c.evidence.map(e=>e.term),embedding_ready_text:`${c.company_name}. ${c.industry}. ${tags(c).join(", ")}.`}));return page("Tender AI Context","Separater Kontext für semantische Suche und Tender-Matching",`<div class="panel"><p class="muted">Der Tender-Kontext wird getrennt vom Sales-Ergebnis exportiert. API-Schlüssel werden nicht exportiert.</p><div class="code">${esc(JSON.stringify(rows.slice(0,2),null,2))}</div></div>`,"<button class=\"btn green\" data-action=\"exportTender\">JSONL exportieren</button>")}
function azure(){const a=state.azure;const u=buildAzureUrl(a);return page("Azure AI Setup","Azure OpenAI-Verbindung für bidirektionale Analysen",`<div class="panel"><div class="alert warn"><b>Wichtig:</b> Der Endpoint darf nur der Ressourcen-Host sein. Die Anwendung verwendet ausschließlich den unten angezeigten URL-Builder.</div><div class="form-grid"><label>Azure OpenAI Endpoint<input id="azEndpoint" value="${esc(a.endpoint)}" placeholder="https://name.openai.azure.com"></label><label>Deployment-Name<input id="azDeployment" value="${esc(a.deployment)}" placeholder="GPT-Deployment"></label><label>API-Version<select id="azVersion"><option ${a.apiVersion==="2025-04-01-preview"?"selected":""}>2025-04-01-preview</option><option ${a.apiVersion==="2024-10-21"?"selected":""}>2024-10-21</option><option ${a.apiVersion==="2024-08-01-preview"?"selected":""}>2024-08-01-preview</option></select></label><label>API-Schlüssel<input id="azKey" type="password" value="${esc(a.apiKey)}" placeholder="Azure OpenAI API-Key"></label></div><div class="toolbar" style="margin-top:14px"><button class="btn" data-action="saveAzure">Speichern</button><button class="btn primary" data-action="testAzure">Verbindung testen</button>${badge(a.status.state==="ok"?"Azure verbunden":a.status.state==="error"?"Azure Fehler":"Nicht getestet")}</div><div class="alert ${a.status.state==="ok"?"ok":a.status.state==="error"?"err":"warn"}">${esc(a.status.message||"Noch kein Verbindungstest ausgeführt.")}</div><h3>Effektive Request-URL</h3><div class="code">${esc(u)}</div><p class="muted">Bei direktem Öffnen über file:// kann Azure den Browseraufruf wegen CORS blockieren. Ein solcher Fehler wird separat geloggt. Die URL darf aber niemals doppelt aufgebaut werden.</p></div>`)}
function diagnostics(){return page("Diagnose & Tests","Lokale Unit Tests und optionaler echter Azure-Live-Test",`<div class="toolbar"><button class="btn primary" data-action="runTests">Unit Tests ausführen</button><button class="btn" data-action="runAzureTest">Tests + Azure Live-Test</button><button class="btn" data-action="downloadLog">Logfile herunterladen</button><button class="btn danger" data-action="clearLog">Log löschen</button></div><div id="testResults" class="panel" style="margin-top:14px">${state.testResults||'<div class="empty">Noch keine Tests ausgeführt.</div>'}</div><div class="panel"><h3>Log</h3><div class="code">${esc(logLines.join("\n")||"Noch keine Logeinträge.")}</div></div>`)}
function buildAzureUrl(raw){let ep=String(raw?.endpoint||"").trim();if(!ep)return"";if(!/^https?:\/\//i.test(ep))ep="https://"+ep;let base;try{base=new URL(ep).origin}catch(e){base=ep.replace(/\/openai\/.*$/i,"").replace(/[?#].*$/,"").replace(/\/+$/,"")}let dep=String(raw?.deployment||"").trim().replace(/^.*\/deployments\//i,"").split("/")[0];let ver=String(raw?.apiVersion||"").trim();if(!/^\d{4}-\d{2}-\d{2}(?:-preview)?$/.test(ver))ver="2025-04-01-preview";return dep?`${base}/openai/deployments/${encodeURIComponent(dep)}/chat/completions?api-version=${encodeURIComponent(ver)}`:""}
function validateAzureUrl(url){const e=[];if((url.match(/\/openai\/deployments\//g)||[]).length!==1)e.push("Deployment-Pfad muss genau einmal vorkommen");if((url.match(/\/chat\/completions/g)||[]).length!==1)e.push("Chat-Completion-Pfad muss genau einmal vorkommen");if(url.includes("/openai/responses"))e.push("Responses-Pfad ist nicht zulässig");if(/chat\/completions[^?#]*\/openai\//i.test(url))e.push("Nach chat/completions folgt ein weiterer Azure-Pfad");if(e.length)throw new Error(e.join("; "));return true}
function log(level,event,data={}){const safe=Object.assign({},data);delete safe.apiKey;delete safe.key;const line=new Date().toISOString()+" ["+level+"] "+event+" "+JSON.stringify(safe);logLines.push(line);if(logLines.length>500)logLines.shift();return line}
async function azureChat(messages,{maxTokens=800,temperature=0}={}){const a=state.azure,url=buildAzureUrl(a);if(!url)throw new Error("Azure-Konfiguration unvollständig");validateAzureUrl(url);log("INFO","azure_request_prepared",{url});let useCompletionTokens=false,dropTemp=false;for(let attempt=0;attempt<4;attempt++){const body={messages};if(useCompletionTokens)body.max_completion_tokens=maxTokens;else body.max_tokens=maxTokens;if(!dropTemp&&temperature!=null)body.temperature=temperature;let r;try{r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","api-key":a.apiKey},body:JSON.stringify(body)})}catch(e){log("ERROR","azure_connection_failed",{message:e.message||String(e),url});throw new Error("Netzwerk-/CORS-Fehler: "+(e.message||e))}const text=await r.text();if(r.ok){let content="";try{const j=JSON.parse(text);content=(j.choices&&j.choices[0]&&j.choices[0].message&&j.choices[0].message.content)||""}catch(e){content=text}log("INFO","azure_connection_succeeded",{status:r.status,url,params:{tokenParam:useCompletionTokens?"max_completion_tokens":"max_tokens",temperature:dropTemp?"default":temperature}});return content}const d=text.toLowerCase();if(r.status===400){if(!useCompletionTokens&&/max_tokens/.test(d)&&(/max_completion_tokens/.test(d)||/not supported|unsupported/.test(d))){log("INFO","azure_retry_max_completion_tokens",{});useCompletionTokens=true;continue}if(useCompletionTokens&&/max_completion_tokens/.test(d)&&/not supported|unsupported|unknown|unrecognized/.test(d)){useCompletionTokens=false;continue}if(!dropTemp&&/temperature/.test(d)&&/not support|unsupported|does not support|only.*(default|1)/.test(d)){log("INFO","azure_retry_drop_temperature",{});dropTemp=true;continue}}log("ERROR","azure_http_error",{status:r.status,detail:text.slice(0,300),url});const hint=r.status===401?" — API-Schlüssel prüfen":r.status===404?" — Deployment-Name prüfen":r.status===400?" — Parameter/API-Version prüfen":"";throw new Error(`Azure HTTP ${r.status}: ${text.slice(0,300)}${hint}`)}log("ERROR","azure_fallback_exhausted",{url});throw new Error("Azure-Anfrage schlägt auch nach Parameter-Fallback fehl.")}
async function testAzure(){const a=state.azure;if(!a.endpoint||!a.deployment||!a.apiKey){a.status={state:"error",message:"Endpoint, Deployment-Name und API-Schlüssel sind erforderlich."};save();render();return}try{const out=await azureChat([{role:"system",content:"Antworte ausschließlich mit OK."},{role:"user",content:"Verbindungstest"}]);a.status={state:"ok",message:"Azure AI verbunden. Antwort: "+out.slice(0,100)};log("INFO","azure_test_ok",{})}catch(e){a.status={state:"error",message:e.message};log("ERROR","azure_test_failed",{message:e.message,url:buildAzureUrl(a)});}save();render()}
function formCompany(c={}){const x=normalizeCompany(c);return `<div class="modal-box"><div class="modal-head"><h2>${c.company_id?"Unternehmen bearbeiten":"Unternehmen hinzufügen"}</h2><button class="btn" data-close>×</button></div><div class="form-grid"><label>Company ID<input id="f_id" value="${esc(x.company_id)}"></label><label>Firmenname<input id="f_name" value="${esc(x.company_name)}"></label><label>Website<input id="f_url" value="${esc(x.website_url)}"></label><label>Rechtsform<input id="f_legal" value="${esc(x.legal_form)}"></label><label>Branche<input id="f_industry" value="${esc(x.industry)}"></label><label>NACE-Code<input id="f_nace" value="${esc(x.nace_code)}"></label><label>NACE-Bezeichnung<input id="f_nacelabel" value="${esc(x.nace_label)}"></label><label>Mitarbeiterklasse<input id="f_emp" value="${esc(x.employee_range)}"></label><label>Ort<input id="f_city" value="${esc(x.city)}"></label><label>Land<input id="f_country" value="${esc(x.country)}"></label><label>CRM-Umsatz<input id="f_rev" type="number" value="${Number(x.crm_revenue||0)}"></label><label>Priorität<select id="f_prio">${["A","B","C","D"].map(p=>`<option ${x.priority===p?"selected":""}>${p}</option>`).join("")}</select></label><label class="full">Tags / Suchbegriffe (Komma getrennt)<input id="f_tags" value="${esc(x.raw_tags.join(", "))}"></label><label class="full">Notizen<textarea id="f_notes">${esc(x.notes)}</textarea></label></div><div class="toolbar" style="margin-top:14px"><button class="btn primary" data-save-company="${esc(x.company_id)}">Speichern</button><button class="btn" data-close>Abbrechen</button></div></div>`}
function openCompany(id=""){const c=id?state.companies.find(x=>x.company_id===id):{};const m=document.querySelector("#modal");m.innerHTML=formCompany(c);m.classList.remove("hidden");m.querySelectorAll("[data-close]").forEach(x=>x.onclick=closeModal);m.querySelector("[data-save-company]").onclick=()=>saveCompany(id)}
function saveCompany(oldId){const v=id=>document.querySelector("#"+id)?.value||"";const c=normalizeCompany({company_id:v("f_id").trim()||"CRM-"+Date.now(),company_name:v("f_name").trim()||"Unbenannt",website_url:v("f_url").trim(),legal_form:v("f_legal").trim(),industry:v("f_industry").trim(),nace_code:v("f_nace").trim(),nace_label:v("f_nacelabel").trim(),employee_range:v("f_emp").trim(),city:v("f_city").trim(),country:v("f_country").trim(),crm_revenue:Number(v("f_rev"))||0,priority:v("f_prio"),raw_tags:v("f_tags").split(",").map(x=>x.trim()).filter(Boolean),notes:v("f_notes")});const i=state.companies.findIndex(x=>x.company_id===oldId);if(i>=0){c.tags=state.companies[i].tags;c.evidence=state.companies[i].evidence;c.crawl_status=state.companies[i].crawl_status;c.opportunity_score=state.companies[i].opportunity_score;c.clusters=state.companies[i].clusters;state.companies[i]=c}else state.companies.push(c);save();closeModal();render();toast("Unternehmen gespeichert")}
function closeModal(){document.querySelector("#modal").classList.add("hidden")}
function exportFile(name,content,type="application/json"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{let data=JSON.parse(reader.result);if(!Array.isArray(data))data=data.companies||[];state.companies=data.map(normalizeCompany);save();render();toast("Daten importiert")}catch(e){toast("Importfehler: "+e.message)}};reader.readAsText(file)}
function csv(rows){return rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\n")}
function exportClusters(){const rows=[["cluster_id","cluster_name","company_id","company_name","matched_tags"]];CLUSTERS.forEach(cl=>state.companies.filter(c=>matchClusters(c).includes(cl.name)).forEach(c=>rows.push([cl.id,cl.name,c.company_id,c.company_name,tags(c).join("|")])));exportFile("crm_clusters.csv",csv(rows),"text/csv")}
function exportTender(){const rows=state.companies.map(c=>JSON.stringify({company_id:c.company_id,company_name:c.company_name,capability_profile:[...c.tags.business_areas,...c.tags.technologies],tender_categories:c.tags.business_areas,relevance_signals:c.evidence.map(e=>e.term),embedding_ready_text:`${c.company_name}. ${c.industry}. ${tags(c).join(", ")}.`})).join("\n");exportFile("tender_ai_context.jsonl",rows,"application/x-ndjson")}
function backup(){const x=JSON.parse(JSON.stringify(state));x.azure.apiKey="";exportFile("also-crm-backup.json",JSON.stringify(x,null,2))}
function runTests(live=false){const results=[];function t(name,fn){try{fn();results.push({name,ok:true,msg:"OK"})}catch(e){results.push({name,ok:false,msg:e.message})}}t("URL normalisiert",()=>{const u=buildAzureUrl({endpoint:"https://x.openai.azure.com/openai/responses?api-version=bad",deployment:"D",apiVersion:"0205-04-01-preview"});if(u!=="https://x.openai.azure.com/openai/deployments/D/chat/completions?api-version=2025-04-01-preview")throw Error(u)});t("URL nicht doppelt",()=>{const u=buildAzureUrl({endpoint:"https://x.openai.azure.com/openai/deployments/D/chat/completions?api-version=2025-04-01-preview",deployment:"D",apiVersion:"2025-04-01-preview"});validateAzureUrl(u)});t("Crawling erzeugt Tags",()=>{const c=normalizeCompany({company_name:"Test Microsoft Azure",raw_tags:[]});crawlCompany(c);if(!tags(c).length)throw Error("Keine Tags")});t("Cluster berechenbar",()=>{const c=normalizeCompany({company_name:"Test",tags:{manufacturers:["Microsoft"],technologies:["Azure"],business_areas:["Cloud Services"]}});if(!matchClusters(c).length)throw Error("Kein Cluster")});t("Log schützt Schlüssel",()=>{const before=logLines.length;log("INFO","secret_test",{apiKey:"DO_NOT_LOG"});if(logLines.slice(before).join("").includes("DO_NOT_LOG"))throw Error("API-Key geloggt")});if(live){return (async()=>{try{await testAzure();results.push({name:"Azure Live-Verbindung",ok:state.azure.status.state==="ok",msg:state.azure.status.message})}catch(e){results.push({name:"Azure Live-Verbindung",ok:false,msg:e.message})}showTests(results)})()}showTests(results)}
function showTests(rs){state.testResults=rs.map(r=>`<div class="list-item">${r.ok?"✅":"❌"} <b>${esc(r.name)}</b><div class="muted">${esc(r.msg)}</div></div>`).join("");log("INFO","unit_tests_completed",{passed:rs.filter(x=>x.ok).length,failed:rs.filter(x=>!x.ok).length});render()}
function render(){const main=document.querySelector("#main");main.innerHTML=({dashboard,companies,raw,tags:tagsView,clusters,sales,tender,azure,diagnostics}[view]||dashboard)();document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===view));bind()}
function bind(){document.querySelectorAll("[data-view]").forEach(n=>n.onclick=()=>{view=n.dataset.view;render()});document.querySelectorAll('[data-action="add"]').forEach(n=>n.onclick=()=>openCompany());document.querySelectorAll('[data-action="crawlAll"]').forEach(n=>n.onclick=()=>{state.companies.forEach(c=>crawlCompany(c));render();toast("Alle Unternehmen gecrawlt")});document.querySelectorAll("[data-crawl]").forEach(n=>n.onclick=()=>{const c=state.companies.find(x=>x.company_id===n.dataset.crawl);if(c){crawlCompany(c);render();toast("Crawling abgeschlossen")}});document.querySelectorAll("[data-edit]").forEach(n=>n.onclick=()=>openCompany(n.dataset.edit));document.querySelectorAll("[data-delete]").forEach(n=>n.onclick=()=>{state.companies=state.companies.filter(c=>c.company_id!==n.dataset.delete);save();render();toast("Unternehmen gelöscht")});document.querySelectorAll('[data-action="backup"]').forEach(n=>n.onclick=backup);document.querySelectorAll('[data-action="import"]').forEach(n=>n.onclick=()=>document.querySelector("#fileImport").click());document.querySelector("#fileImport").onchange=e=>importData(e.target.files[0]);document.querySelectorAll('[data-action="exportClusters"]').forEach(n=>n.onclick=exportClusters);document.querySelectorAll('[data-action="exportTender"]').forEach(n=>n.onclick=exportTender);document.querySelectorAll('[data-action="saveAzure"]').forEach(n=>n.onclick=()=>{state.azure.endpoint=document.querySelector("#azEndpoint").value.trim();state.azure.deployment=document.querySelector("#azDeployment").value.trim();state.azure.apiVersion=document.querySelector("#azVersion").value;state.azure.apiKey=document.querySelector("#azKey").value.trim();save();render();toast("Azure-Konfiguration gespeichert")});document.querySelectorAll('[data-action="testAzure"]').forEach(n=>n.onclick=()=>{state.azure.endpoint=document.querySelector("#azEndpoint").value.trim();state.azure.deployment=document.querySelector("#azDeployment").value.trim();state.azure.apiVersion=document.querySelector("#azVersion").value;state.azure.apiKey=document.querySelector("#azKey").value.trim();save();testAzure()});document.querySelectorAll('[data-action="runTests"]').forEach(n=>n.onclick=()=>runTests(false));document.querySelectorAll('[data-action="runAzureTest"]').forEach(n=>n.onclick=()=>runTests(true));document.querySelectorAll('[data-action="downloadLog"]').forEach(n=>n.onclick=()=>exportFile("also-diagnostics.log",logLines.join("\n"),"text/plain"));document.querySelectorAll('[data-action="clearLog"]').forEach(n=>n.onclick=()=>{logLines=[];render()})}
if(!state.companies.length){state.companies=[];save()}render();
})();